
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fernando
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Treasurer");
    }
    public Image getIconImage()
    {
Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/Imagenes/Logo.png"));
	return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado = new javax.swing.JLabel();
        botonConsulta = new javax.swing.JLabel();
        botonIngreso = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conexion con = new conexion();
        if (con.estadoConexion() == false){
            estado.setText("desconectado");
            estado.setForeground(new java.awt.Color(255, 0, 0));}
        if (con.estadoConexion()== true){
            estado.setForeground(new java.awt.Color(0, 204, 51));
            estado.setText("conectado");
        }
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 90, 20));

        botonConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultaMouseClicked(evt);
            }
        });
        getContentPane().add(botonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 380, 60));

        botonIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresoMouseClicked(evt);
            }
        });
        getContentPane().add(botonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 380, 60));

        About.setForeground(new java.awt.Color(204, 204, 204));
        About.setText("Mas informacion");
        getContentPane().add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bases.png"))); // NOI18N
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoMouseClicked(evt);
            }
        });
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_FondoMouseClicked

    private void botonIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseClicked
    IngresarDatos ingresar = new IngresarDatos();
    this.setVisible(false);
    ingresar.setVisible(true);
    
// TODO add your handling code here:
    }//GEN-LAST:event_botonIngresoMouseClicked

    private void botonConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultaMouseClicked
    ConsultarDatos con = new ConsultarDatos();
    this.setVisible(false);
    con.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_botonConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel botonConsulta;
    private javax.swing.JLabel botonIngreso;
    private javax.swing.JLabel estado;
    // End of variables declaration//GEN-END:variables
}
